-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) TOTAL_SALES
FROM AUTHOR
JOIN BOOK
USING (AUTHOR_ID)
JOIN (
    SELECT BOOK_ID, SUM(SALES) SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
) a
USING (BOOK_ID)
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC