-- 코드를 작성해주세요
SELECT ID, IFNULL(CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA a
LEFT JOIN (
      SELECT COUNT(*) AS CHILD_COUNT, PARENT_ID
      FROM ECOLI_DATA
      GROUP BY PARENT_ID
) b
ON a.ID=b.PARENT_ID