WITH CANTRENT AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE>='2022-11-01' AND START_DATE<='2022-12-01'
)
SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE*30*(100-DISCOUNT_RATE)/100, 0) FEE
FROM CAR_RENTAL_COMPANY_CAR
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '30%'
) a
USING (CAR_TYPE)
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CANTRENT) AND (CAR_TYPE='SUV' OR CAR_TYPE='세단')
GROUP BY CAR_ID
HAVING 500000<=FEE AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC