-- 코드를 작성해주세요
SELECT ID, 
    CASE 
        WHEN `RANK`<=0.25 THEN 'LOW' 
        WHEN 0.25<`RANK` AND `RANK`<=0.5 THEN 'MEDIUM' 
        WHEN 0.5<`RANK` AND `RANK`<=0.75 THEN 'HIGH' 
        WHEN 0.75<`RANK` THEN 'CRITICAL' 
    END AS COLONY_NAME
FROM ECOLI_DATA
JOIN (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS `RANK`
    FROM ECOLI_DATA
) b
USING (ID)