-- 코드를 입력하세요
SELECT ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_INS a
LEFT JOIN ANIMAL_OUTS b
USING (ANIMAL_ID)
WHERE SEX_UPON_INTAKE LIKE 'Intact%' and SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY ANIMAL_ID