-- 코드를 입력하세요
SELECT YEAR, MONTH, COUNT(SALES_AMOUNT) PURCHASED_USERS, ROUND(COUNT(SALES_AMOUNT)/(
    SELECT COUNT(USER_ID)
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'), 1) PUCHASED_RATIO
FROM USER_INFO
JOIN (
    SELECT USER_ID, SALES_AMOUNT, YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH
    FROM ONLINE_SALE
    GROUP BY YEAR, MONTH, USER_ID
) b
USING (USER_ID)
WHERE JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH