-- 코드를 입력하세요
SELECT CAR_ID, CASE WHEN COUNT(`1`)>0 THEN '대여중' ELSE '대여 가능' END AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
LEFT JOIN(
    SELECT 1, CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE<='2022-10-16' AND END_DATE>='2022-10-16'
    GROUP BY CAR_ID
) b
USING (CAR_ID)
GROUP BY CAR_ID
ORDER BY CAR_ID DESC