-- 코드를 입력하세요
WITH idINFO AS (
    SELECT PRODUCT_ID, PRODUCT_NAME, PRICE
    FROM FOOD_PRODUCT
)
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT)*PRICE TOTAL_SALES
FROM FOOD_ORDER
JOIN idINFO
USING (PRODUCT_ID)
WHERE PRODUCE_DATE LIKE '2022-05-%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID