-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW
LEFT JOIN MEMBER_PROFILE
USING (MEMBER_ID)
JOIN (
    SELECT MEMBER_ID, DENSE_RANK() OVER (ORDER BY COUNT(REVIEW_ID) DESC) R
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) b
USING (MEMBER_ID)
WHERE R=1
ORDER BY REVIEW_DATE, REVIEW_TEXT