-- 코드를 작성해주세요
SELECT a.ID, a.GENOTYPE, b.PARENT_GENOTYPE
FROM ECOLI_DATA a
JOIN (
    SELECT GENOTYPE PARENT_GENOTYPE, ID
    FROM ECOLI_DATA  
    ) b
ON a.PARENT_ID=b.ID
WHERE GENOTYPE & PARENT_GENOTYPE = PARENT_GENOTYPE
ORDER BY ID