-- 코드를 작성해주세요
WITH `MAX` AS(
    SELECT FISH_TYPE, MAX(LENGTH) MAXSIZE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO
JOIN `MAX`
USING (FISH_TYPE)
JOIN FISH_NAME_INFO
USING (FISH_TYPE)
WHERE MAXSIZE=LENGTH
ORDER BY ID