-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, b.FILE_NAME, b.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD
JOIN (
    SELECT BOARD_ID, FILE_EXT, FILE_NAME, FILE_ID
    FROM USED_GOODS_FILE
) b
USING (BOARD_ID)
WHERE VIEWS=(SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC